language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - python django_dialogflow/manage.py test django_dialogflow.tests

after_success:
  - coveralls
